force-app/main/default/objects/Invitation__c/Invitation__c.object-meta.xml
<CustomObject>
    <description>This Object is Used in Invitation App</description>
    <label>Invitation</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invitation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invitation__c/fields/Event_Address__c.field-meta.xml
<CustomField>
    <fullName>Event_Address__c</fullName>
    <label>Event Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_and_Time__c</fullName>
    <label>Event Date and Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Introduction__c.field-meta.xml
<CustomField>
    <fullName>Event_Introduction__c</fullName>
    <label>Event Introduction</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Map_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_Map_URL__c</fullName>
    <label>Event Map URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Participants__c.field-meta.xml
<CustomField>
    <fullName>Event_Participants__c</fullName>
    <label>Event Participants</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Facebook_Url__c.field-meta.xml
<CustomField>
    <fullName>Facebook_Url__c</fullName>
    <label>Facebook Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Greeting_Message__c.field-meta.xml
<CustomField>
    <fullName>Greeting_Message__c</fullName>
    <label>Greeting Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Instagram_Url__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Url__c</fullName>
    <label>Instagram Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>theme1</fullName>
            </value>
            <value>
                <fullName>theme2</fullName>
            </value>
            <value>
                <fullName>theme3</fullName>
            </value>
            <value>
                <fullName>theme4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Detail__c/Program_Detail__c.object-meta.xml
<CustomObject>
    <label>Program Detail</label>
    <nameField>
        <label>Program Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Detail__c/fields/Invitation__c.field-meta.xml
<CustomField>
    <fullName>Invitation__c</fullName>
    <label>Invitation</label>
    <referenceTo>Invitation__c</referenceTo>
    <relationshipLabel>Program Details</relationshipLabel>
    <relationshipName>Program_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Detail__c/fields/Program_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Date__c</fullName>
    <label>Program Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Detail__c/fields/Program_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Time__c</fullName>
    <label>Program End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Program_Detail__c/fields/Program_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Time__c</fullName>
    <label>Program Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/InvitationController.cls
public without sharing class InvitationController {
    
    //Get Invitation details by Id
    @AuraEnabled(cacheable=true)
    public static Invitation__c getInvitationDetailsById(String Id){
        try{
            return [SELECT Id, Twitter_Url__c, Theme__c, Instagram_Url__c, Greeting_Message__c, Facebook_Url__c, Event_Participants__c,
            Event_Introduction__c, Event_Date_and_Time__c from Invitation__c where Id= : Id];
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Program_Detail__c> getProgramDetailsByInvitationId(String Id){
        try{
            return [SELECT Id, Program_Date__c ,Invitation__c ,Name ,Program_End_Time__c,Program_Start_Time__c  from Program_Detail__c where Invitation__c=: Id];
            
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Invitation__c> getInvitationAddress(String Id){
        try{
            return [SELECT Id, Event_Address__c ,Greeting_Message__c ,Event_Map_URL__c ,Contact_Number__c   from Invitation__c  where Id=: Id];
            
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        
    }
}